# Generated by Django 5.2.12 on 2026-04-26 06:46

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_default_bank_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                default="America/Los_Angeles",
                max_length=100,
                validators=[users.models.validate_timezone],
            ),
        ),
    ]
