# Generated by Django 5.2.12 on 2026-07-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="expiry_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
