# Generated by Django 5.2.12 on 2026-05-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="sender_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
