# Generated by Django 5.2.12 on 2026-05-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_sender_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="sender_id",
        ),
    ]
