# Generated by Django 5.2.12 on 2026-06-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notificationpreference_delivery_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelpreference",
            name="digest_frequency",
            field=models.CharField(
                choices=[
                    ("daily_morning", "Once daily (morning, ~7 am)"),
                    ("daily_evening", "Once daily (evening, ~6 pm)"),
                    ("twice_daily", "Twice daily (morning + evening)"),
                    ("weekly_friday", "Weekly on Friday"),
                    ("weekly_saturday", "Weekly on Saturday"),
                    ("weekly_sunday", "Weekly on Sunday"),
                ],
                default="daily_morning",
                max_length=20,
            ),
        ),
    ]
