volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

services:
  django: &django
    build:
      context: ..
      target: prod
    image: mibudge:prod
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env.production
    command: /app/scripts/start_app.sh

  postgres:
    image: postgres:16-alpine
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file: .env.production
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  celeryworker:
    <<: *django
    image: mibudge:prod
    command: /app/scripts/start_celeryworker.sh

  celerybeat:
    <<: *django
    image: mibudge:prod
    command: /app/scripts/start_celerybeat.sh

  flower:
    <<: *django
    image: mibudge:prod
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "5555:5555"
    command: /app/scripts/start_flower.sh
