# Generated by Django 5.2.12 on 2026-04-02 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("moneypools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="owners",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="budget",
            name="bank_account",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="moneypools.bankaccount",
                to_field="id",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="fillup_goal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="moneypools.budget",
                to_field="id",
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="unallocated_budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="moneypools.budget",
                to_field="id",
            ),
        ),
        migrations.AddField(
            model_name="internaltransaction",
            name="actor",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="internaltransaction",
            name="bank_account",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="moneypools.bankaccount",
                to_field="id",
            ),
        ),
        migrations.AddField(
            model_name="internaltransaction",
            name="dst_budget",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_credits",
                to="moneypools.budget",
                to_field="id",
            ),
        ),
        migrations.AddField(
            model_name="internaltransaction",
            name="src_budget",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_debits",
                to="moneypools.budget",
                to_field="id",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="bank_account",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="moneypools.bankaccount",
                to_field="id",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="moneypools.budget",
                to_field="id",
            ),
        ),
    ]
