# Generated by Django 5.2.12 on 2026-04-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0002_remove_transaction_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="target_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
