# Generated by Django 5.2.12 on 2026-04-07 23:04

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0003_alter_budget_target_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=encrypted_fields.fields.EncryptedCharField(
                default=None, editable=False, max_length=12, null=True, unique=True
            ),
        ),
    ]
