# Generated by Django 5.2.12 on 2026-04-11 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0005_bank_default_currency_bankaccount_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="linked_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_from",
                to="moneypools.transaction",
                to_field="id",
            ),
        ),
    ]
