# Generated by Django 5.2.12 on 2026-04-12 08:32

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0008_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, default=None, max_length=12, null=True, unique=True
            ),
        ),
    ]
