# Generated by Django 5.2.12 on 2026-04-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0009_alter_bankaccount_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("signature_purchase", "Signature Purchase"),
                    ("ach", "ACH"),
                    ("round-up_transfer", "Round-up Transfer"),
                    (
                        "protected_goal_account_transfer",
                        "Protected Goal Account Transfer",
                    ),
                    ("fee", "Fee"),
                    ("pin_purchase", "Pin Purchase"),
                    ("signature_credit", "Signature Credit"),
                    ("interest_credit", "Interest Credit"),
                    ("shared_transfer", "Shared Transfer"),
                    ("courtesy_credit", "Courtesy Credit"),
                    ("atm_withdrawal", "ATM Withdrawal"),
                    ("bill_payment", "Bill Payment"),
                    ("bank_generated_credit", "Bank Generated Credit"),
                    ("wire_transfer", "Wire Transfer"),
                    ("check_deposit", "Check Deposit"),
                    ("check", "Check"),
                    ("c2c", "c2c"),
                    ("migration_interbank_transfer", "Migration Interbank Transfer"),
                    ("balance_sweep", "Balance Sweep"),
                    ("ach_reversal", "ACH Reversal"),
                    ("adjustment", "Adjustment"),
                    ("signature_return", "Signature return"),
                    ("fx_order", "FX Order"),
                    ("", "--------"),
                ],
                max_length=32,
            ),
        ),
    ]
