# Generated by Django 5.2.12 on 2026-04-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0011_alter_bankaccount_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="routing_number",
            field=models.CharField(
                blank=True, default=None, max_length=9, null=True, unique=True
            ),
        ),
    ]
