# Generated by Django 5.2.12 on 2026-04-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0012_alter_bank_routing_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="link_aliases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Substrings that may appear in a counterpart transaction\'s description to identify this account (e.g. "CHASE CREDIT CRD"). Case-insensitive.',
            ),
        ),
    ]
