# Generated by Django 5.2.12 on 2026-04-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0013_bankaccount_link_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="complete",
            field=models.BooleanField(
                default=False,
                help_text="True when this budget has reached its target and should not be funded further.  Managed by signals and funding tasks; do not set manually.",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="budget_type",
            field=models.CharField(
                choices=[
                    ("G", "Goal"),
                    ("R", "Recurring"),
                    ("A", "Associated Fill-up Goal"),
                    ("C", "Capped"),
                ],
                default="G",
                max_length=1,
            ),
        ),
    ]
