# Generated by Django 5.2.12 on 2026-04-16 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0014_budget_complete_alter_budget_budget_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="internaltransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("src_budget_id", models.F("dst_budget_id")), _negated=True
                ),
                name="internal_transaction_src_dst_different",
            ),
        ),
    ]
