# Generated by Django 5.2.12 on 2026-04-16 07:01

import djmoney.models.fields
import moneypools.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "moneypools",
            "0015_internaltransaction_internal_transaction_src_dst_different",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="funding_amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=None,
                default_currency=moneypools.models.get_default_currency,
                help_text="Amount credited per funding event (Fixed Amount funding type only).",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="funding_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("BRL", "Brazilian Real"),
                    ("GBP", "British Pound"),
                    ("CAD", "Canadian Dollar"),
                    ("CNY", "Chinese Yuan"),
                    ("DKK", "Danish Krone"),
                    ("EUR", "Euro"),
                    ("HKD", "Hong Kong Dollar"),
                    ("INR", "Indian Rupee"),
                    ("JPY", "Japanese Yen"),
                    ("MXN", "Mexican Peso"),
                    ("TWD", "New Taiwan Dollar"),
                    ("NZD", "New Zealand Dollar"),
                    ("NOK", "Norwegian Krone"),
                    ("SGD", "Singapore Dollar"),
                    ("ZAR", "South African Rand"),
                    ("KRW", "South Korean Won"),
                    ("SEK", "Swedish Krona"),
                    ("CHF", "Swiss Franc"),
                    ("USD", "US Dollar"),
                ],
                default=moneypools.models.get_default_currency,
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
    ]
