# Generated by Django 5.2.12 on 2026-04-16 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0017_create_missing_fillup_goal_budgets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="fillup_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="moneypools.budget",
                to_field="id",
            ),
        ),
    ]
