# Generated by Django 5.2.12 on 2026-04-26 02:27

from django.db import migrations, models


def backfill_posted_date(apps, schema_editor):
    """Copy transaction_date -> posted_date for all existing rows."""
    Transaction = apps.get_model("moneypools", "Transaction")
    Transaction.objects.filter(posted_date__isnull=True).update(
        posted_date=models.F("transaction_date")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0019_fix_running_balances"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="posted_date",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.RunPython(
            backfill_posted_date,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
