# Generated by Django 5.2.12 on 2026-04-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0022_transaction_posted_date_non_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="last_imported_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Wall-clock time of the most recent completed import for this account.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="last_posted_through",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Latest posted_date seen in the most recent import batch. The funding engine will not process events dated after this value.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="last_funded_on",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Date of the most recently processed funding event for this budget.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="last_recurrence_on",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Date of the most recently processed recurrence event. Only meaningful for Recurring budgets with with_fillup_goal=True.",
                null=True,
            ),
        ),
    ]
