# Generated by Django 5.2.12 on 2026-05-11 17:12

import djmoney.models.fields
import moneypools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0026_rename_recurrance_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="with_fillup_goal",
        ),
        migrations.AddField(
            model_name="budget",
            name="funded_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=moneypools.models.get_default_zero,
                default_currency=moneypools.models.get_default_currency,
                help_text="For Goal budgets: running net of all ITX credits minus debits. Unused for other types.",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="funded_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("BRL", "Brazilian Real"),
                    ("GBP", "British Pound"),
                    ("CAD", "Canadian Dollar"),
                    ("CNY", "Chinese Yuan"),
                    ("DKK", "Danish Krone"),
                    ("EUR", "Euro"),
                    ("HKD", "Hong Kong Dollar"),
                    ("INR", "Indian Rupee"),
                    ("JPY", "Japanese Yen"),
                    ("MXN", "Mexican Peso"),
                    ("TWD", "New Taiwan Dollar"),
                    ("NZD", "New Zealand Dollar"),
                    ("NOK", "Norwegian Krone"),
                    ("SGD", "Singapore Dollar"),
                    ("ZAR", "South African Rand"),
                    ("KRW", "South Korean Won"),
                    ("SEK", "Swedish Krona"),
                    ("CHF", "Swiss Franc"),
                    ("USD", "US Dollar"),
                ],
                default=moneypools.models.get_default_currency,
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="internaltransaction",
            name="system_event_date",
            field=models.DateField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="internaltransaction",
            name="system_event_kind",
            field=models.CharField(
                blank=True,
                choices=[("F", "Fund"), ("R", "Recur")],
                default=None,
                editable=False,
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="last_recurrence_on",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Date of the most recently processed recurrence event. Only meaningful for Recurring budgets.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("budget_type", "R"), ("funding_type", "D")),
                    models.Q(("budget_type", "R"), _negated=True),
                    _connector="OR",
                ),
                name="budget_recurring_must_be_target_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("budget_type", "C"), ("funding_type", "F")),
                    models.Q(("budget_type", "C"), _negated=True),
                    _connector="OR",
                ),
                name="budget_capped_must_be_fixed_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("budget_type", "R"), ("target_date__isnull", True)),
                    models.Q(("budget_type", "C"), ("target_date__isnull", True)),
                    models.Q(("budget_type__in", ["R", "C"]), _negated=True),
                    _connector="OR",
                ),
                name="budget_recurring_capped_no_target_date",
            ),
        ),
    ]
