# Generated by Django 5.2.12 on 2026-05-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0028_funding_redesign_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="bank_transaction_id",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=256, null=True
            ),
        ),
    ]
