# Generated by Django 5.2.12 on 2026-05-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0029_transaction_bank_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internaltransaction",
            name="effective_date",
            field=models.DateTimeField(editable=False),
        ),
    ]
