# Generated by Django 5.2.12 on 2026-06-03 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypools', '0030_alter_internaltransaction_effective_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingEventOccurrence',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(help_text='Funding event discriminator: "fund" or "recur".  Stored as the EventKind string value; not exposed in user-facing forms so no choices= is set.', max_length=5)),
                ('scheduled_date', models.DateField(help_text='Calendar date the event was scheduled to fire.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('COMPLETE', 'Complete'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=8)),
                ('completed_at', models.DateTimeField(blank=True, default=None, help_text='Wall-clock time the occurrence reached COMPLETE.  Null while PENDING/PARTIAL/SKIPPED.', null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_occurrences', to='moneypools.budget', to_field='id')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('status__in', ['PENDING', 'PARTIAL'])), fields=['budget', 'scheduled_date'], name='funding_event_occ_outstanding')],
                'constraints': [models.UniqueConstraint(fields=('budget', 'kind', 'scheduled_date'), name='funding_event_occ_unique_per_event')],
            },
        ),
    ]
