# Generated by Django 5.2.12 on 2026-06-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypools', '0031_funding_event_occurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='auto_funding_enabled',
            field=models.BooleanField(default=True, help_text="When enabled (the default), scheduled funding and recurrence events run automatically for this account.  Disable to opt out of automation and drive funding entirely from the 'Run funding now' button."),
        ),
    ]
