# Generated by Django 5.2.12 on 2026-06-09 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0033_bankaccountinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccountinvitation",
            name="last_sent_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="bankaccountinvitation",
            name="send_count",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
