# Generated by Django 5.2.12 on 2026-07-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0034_bankaccountinvitation_last_sent_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="group",
        ),
    ]
