# Generated by Django 5.2.12 on 2026-07-17 02:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0040_transaction_category_and_auto_spend"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="description_user_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="details",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant_address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant_category",
            field=models.CharField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant_category_code",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant_city",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant_country",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{2}$", "Must be an ISO 3166-1 alpha-2 country code."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-90")),
                    django.core.validators.MaxValueValidator(Decimal("90")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-180")),
                    django.core.validators.MaxValueValidator(Decimal("180")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant_name",
            field=models.CharField(
                blank=True, editable=False, max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant_region",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="virtual_card_number",
            field=models.CharField(
                blank=True, editable=False, max_length=32, null=True
            ),
        ),
    ]
