# Generated by Django 3.2.3 on 2021-05-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="account_type",
            field=models.CharField(
                choices=[("C", "Checking"), ("S", "Savings")],
                default="C",
                max_length=1,
            ),
        ),
    ]
