# Generated by Django 3.2.4 on 2021-07-16 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="account_available_balance",
            new_name="bank_account_available_balance",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="account_available_balance_currency",
            new_name="bank_account_available_balance_currency",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="account_posted_balance",
            new_name="bank_account_posted_balance",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="account_posted_balance_currency",
            new_name="bank_account_posted_balance_currency",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="budget_posted_balance",
            new_name="budget_balance",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="budget_available_balance_currency",
            new_name="budget_balance_currency",
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="unallocated_balance",
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="unallocated_balance_currency",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="budget_available_balance",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="budget_posted_balance_currency",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="unallocated_budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="moneypools.budget",
                to_field="id",
            ),
        ),
    ]
