# Generated by Django 3.2.3 on 2021-06-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneypools', '0002_alter_transaction_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internaltransaction',
            old_name='dest_budget',
            new_name='dst_budget',
        ),
    ]
