# Generated by Django 3.2.3 on 2021-05-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0003_auto_20210526_2320"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="funding_type",
            field=models.CharField(
                choices=[("D", "Target Date"), ("F", "Fixed Amount")],
                default="D",
                max_length=1,
            ),
        ),
    ]
