# Generated by Django 3.2.3 on 2021-06-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0004_budget_funding_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="image_height",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="budget",
            name="image_width",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
