# Generated by Django 3.2.3 on 2021-06-04 07:41

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("moneypools", "0006_auto_20210603_1720"),
    ]

    operations = [
        migrations.RenameField(
            model_name="internaltransaction",
            old_name="dst_budget_available_balance_currency",
            new_name="dst_budget_balance_currency",
        ),
        migrations.RenameField(
            model_name="internaltransaction",
            old_name="src_budget_available_balance_currency",
            new_name="src_budget_balance_currency",
        ),
        migrations.RemoveField(
            model_name="internaltransaction",
            name="dst_budget_available_balance",
        ),
        migrations.RemoveField(
            model_name="internaltransaction",
            name="dst_budget_posted_balance",
        ),
        migrations.RemoveField(
            model_name="internaltransaction",
            name="dst_budget_posted_balance_currency",
        ),
        migrations.RemoveField(
            model_name="internaltransaction",
            name="src_budget_available_balance",
        ),
        migrations.RemoveField(
            model_name="internaltransaction",
            name="src_budget_posted_balance",
        ),
        migrations.RemoveField(
            model_name="internaltransaction",
            name="src_budget_posted_balance_currency",
        ),
        migrations.AddField(
            model_name="internaltransaction",
            name="dst_budget_balance",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                editable=False,
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="internaltransaction",
            name="src_budget_balance",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                editable=False,
                max_digits=14,
            ),
        ),
    ]
